version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: fleetflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleetflow_db
    ports:
      - "5432:5432"
    volumes:
      - fleetflow_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: fleetflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  fleetflow_pgdata:
