from .user import User
from .vehicle import Vehicle
from .driver import Driver
from .shipment import Shipment
from .trip import Trip
from .maintenance import Maintenance
from .driver_assignment import DriverAssignment
from .driver_attendance import DriverAttendance
from .fuel_record import FuelRecord
from .maintenance_alert import MaintenanceAlert