"""sync_models_with_db

Revision ID: 84675ddaeceb
Revises: 20260803_0002
Create Date: 2026-08-07 18:34:46.458905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84675ddaeceb'
down_revision: Union[str, Sequence[str], None] = '20260803_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('alert_status', sa.String(), nullable=False),
    sa.Column('generated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_records.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_alerts_id'), 'maintenance_alerts', ['id'], unique=False)
    op.drop_table('sri')
    op.drop_constraint(op.f('drivers_license_number_key'), 'drivers', type_='unique')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=True)
    op.add_column('maintenance_records', sa.Column('category', sa.String(), nullable=False))
    op.add_column('maintenance_records', sa.Column('next_service_date', sa.Date(), nullable=True))
    op.add_column('maintenance_records', sa.Column('service_provider', sa.String(), nullable=True))
    op.add_column('maintenance_records', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('maintenance_records', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('maintenance_records', sa.Column('is_deleted', sa.Integer(), nullable=False))
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('shipments', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_shipments_tracking_number'), 'shipments', type_='unique')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', type_='unique')
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=False)
    op.create_unique_constraint(op.f('vehicles_vehicle_number_key'), 'vehicles', ['vehicle_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=False)
    op.create_unique_constraint(op.f('uq_shipments_tracking_number'), 'shipments', ['tracking_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('shipments', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintenance_records', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('maintenance_records', 'is_deleted')
    op.drop_column('maintenance_records', 'created_at')
    op.drop_column('maintenance_records', 'notes')
    op.drop_column('maintenance_records', 'service_provider')
    op.drop_column('maintenance_records', 'next_service_date')
    op.drop_column('maintenance_records', 'category')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=False)
    op.create_unique_constraint(op.f('drivers_license_number_key'), 'drivers', ['license_number'], postgresql_nulls_not_distinct=False)
    op.create_table('sri',

    )
    op.drop_index(op.f('ix_maintenance_alerts_id'), table_name='maintenance_alerts')
    op.drop_table('maintenance_alerts')
    # ### end Alembic commands ###
