"""add fuel_records table

Revision ID: 10d9fac431bc
Revises: 33442bad7cf0
Create Date: 2026-08-03 09:51:32.525597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d9fac431bc'
down_revision: Union[str, Sequence[str], None] = '33442bad7cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('fuel_quantity', sa.Float(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('fuel_station', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_records_id'), 'fuel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_records_id'), table_name='fuel_records')
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
