"""Add location fields to trips

Revision ID: 134f5261f8b8
Revises: dfbd1d67e725
Create Date: 2026-07-17 19:06:24.801215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134f5261f8b8'
down_revision: Union[str, Sequence[str], None] = 'dfbd1d67e725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.add_column(
        'trips',
        sa.Column(
            'pickup_latitude',
            sa.Float(),
            nullable=True
        )
    )


    op.add_column(
        'trips',
        sa.Column(
            'pickup_longitude',
            sa.Float(),
            nullable=True
        )
    )


    op.add_column(
        'trips',
        sa.Column(
            'destination_latitude',
            sa.Float(),
            nullable=True
        )
    )


    op.add_column(
        'trips',
        sa.Column(
            'destination_longitude',
            sa.Float(),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'pickup_longitude')
    op.drop_column('trips', 'pickup_latitude')
    # ### end Alembic commands ###
