"""Add driver_assignments and driver_attendance

Revision ID: 5c5689eee45d
Revises: f67c4c4b404b
Create Date: 2026-08-03 15:29:37.055822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5689eee45d'
down_revision: Union[str, Sequence[str], None] = 'f67c4c4b404b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
