"""Add maintenance table

Revision ID: 83fa576eaf1a
Revises: c45006f96cc9
Create Date: 2026-07-29 21:40:34.745460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fa576eaf1a'
down_revision: Union[str, Sequence[str], None] = 'c45006f96cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_category', sa.String(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('next_service_date', sa.DateTime(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.Column('service_provider', sa.String(), nullable=True),
    sa.Column('maintenance_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenances_id'), 'maintenances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenances_id'), table_name='maintenances')
    op.drop_table('maintenances')
    # ### end Alembic commands ###
