"""add latitude longitude to vehicles

Revision ID: 8deac713c425
Revises: ac3c8681a86f
Create Date: 2026-07-05 19:38:49.984655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8deac713c425'
down_revision: Union[str, Sequence[str], None] = 'ac3c8681a86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('eta', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('vehicles', 'fuel_level',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'fuel_level',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('vehicles', 'longitude')
    op.drop_column('vehicles', 'latitude')
    op.drop_column('shipments', 'eta')
    # ### end Alembic commands ###
