"""fix driver_assignments

Revision ID: 9823d1f41829
Revises: 22c55c06c80b
Create Date: 2026-08-02 18:33:07.152714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9823d1f41829'
down_revision: Union[str, Sequence[str], None] = '22c55c06c80b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=True),
    sa.Column('assignment_status', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_driver_assignments_assignment_id'), 'driver_assignments', ['assignment_id'], unique=False)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Available'::character varying"))
    op.execute("""
    ALTER TABLE shipments
    ALTER COLUMN current_status DROP DEFAULT;

    ALTER TABLE shipments
    ALTER COLUMN current_status
    TYPE shipmentstatus
    USING current_status::shipmentstatus;

    ALTER TABLE shipments
    ALTER COLUMN current_status
    SET DEFAULT 'Created';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'current_status',
               existing_type=sa.Enum('Created', 'Assigned', 'Picked Up', 'In Transit', 'Out for Delivery', 'Delivered', 'Delayed', 'Cancelled', name='shipmentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Created'::character varying"))
    op.alter_column('maintenance', 'maintenance_category',
               existing_type=sa.Enum('OIL_CHANGE', 'TYRE_REPLACEMENT', 'BRAKE_SERVICE', 'ENGINE_SERVICE', 'GENERAL_INSPECTION', name='maintenancecategory'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Available'::character varying"))
    op.drop_index(op.f('ix_driver_assignments_assignment_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    # ### end Alembic commands ###
