"""Added shipment fields

Revision ID: ac3c8681a86f
Revises: ff36235e9d9c
Create Date: 2026-07-04 23:54:09.118812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3c8681a86f'
down_revision: Union[str, Sequence[str], None] = 'ff36235e9d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('shipment_type', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'weight')
    op.drop_column('shipments', 'shipment_type')
    # ### end Alembic commands ###
