"""add_trip_coordinates

Revision ID: c45006f96cc9
Revises: b6503f7e48e2
Create Date: 2026-07-29 09:46:35.983261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45006f96cc9'
down_revision: Union[str, Sequence[str], None] = 'b6503f7e48e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('traffic_level', sa.String(), server_default='Normal', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'traffic_level')
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'pickup_longitude')
    op.drop_column('trips', 'pickup_latitude')
    # ### end Alembic commands ###

