"""Add maintenance_alerts table

Revision ID: d1353d60b2d5
Revises: 10d9fac431bc
Create Date: 2026-08-06 09:50:54.837006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1353d60b2d5'
down_revision: Union[str, Sequence[str], None] = '10d9fac431bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('alert_message', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('alert_status', sa.String(), nullable=True),
    sa.Column('generated_date', sa.DateTime(), nullable=True),
    sa.Column('next_service_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenances.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_alerts_id'), 'maintenance_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_alerts_id'), table_name='maintenance_alerts')
    op.drop_table('maintenance_alerts')
    # ### end Alembic commands ###
