"""Added fuel fields to vehicle

Revision ID: ff36235e9d9c
Revises: 33f205d5ba85
Create Date: 2026-07-04 22:39:01.801536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff36235e9d9c'
down_revision: Union[str, Sequence[str], None] = '33f205d5ba85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_level', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_status', sa.String(), nullable=False))
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('vehicles', 'fuel_status')
    op.drop_column('vehicles', 'fuel_level')
    op.drop_column('vehicles', 'fuel_type')
    # ### end Alembic commands ###
