"""add driver assignments table

Revision ID: 29071c2bd69a
Revises: 20260715_add_trip_coordinates
Create Date: 2026-07-30 23:48:29.983559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29071c2bd69a'
down_revision: Union[str, Sequence[str], None] = '20260715_add_trip_coordinates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
