"""Add vehicle fields

Revision ID: b88882ecc2a2
Revises: 0a760f131d9e
Create Date: 2026-07-08 22:56:35.553710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88882ecc2a2'
down_revision: Union[str, Sequence[str], None] = '0a760f131d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add NOT NULL columns with a temporary server_default so existing rows get a value
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=False, server_default='Truck'))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False, server_default='Diesel'))
    op.add_column('vehicles', sa.Column('assigned_driver_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('current_status', sa.String(), nullable=True, server_default='available'))
    op.create_foreign_key(None, 'vehicles', 'drivers', ['assigned_driver_id'], ['id'])
    # Remove the temporary server defaults now that existing rows are filled
    op.alter_column('vehicles', 'vehicle_type', server_default=None)
    op.alter_column('vehicles', 'fuel_type', server_default=None)
    op.alter_column('vehicles', 'current_status', server_default=None)
    op.drop_column('vehicles', 'is_available')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'current_status')
    op.drop_column('vehicles', 'assigned_driver_id')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'vehicle_type')
    # ### end Alembic commands ###
