"""add sender receiver weight and enum status to shipment

Revision ID: 16bed5c476fd
Revises: fc43eeb68af0
Create Date: 2026-07-15 09:14:05.228282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bed5c476fd'
down_revision: Union[str, Sequence[str], None] = 'fc43eeb68af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('sender_name', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('receiver_name', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('weight', sa.Float(), nullable=True))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('created', 'assigned', 'in_transit', 'delayed', 'delivered', 'cancelled', name='shipmentstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipments', 'status',
               existing_type=sa.Enum('created', 'assigned', 'in_transit', 'delayed', 'delivered', 'cancelled', name='shipmentstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('shipments', 'weight')
    op.drop_column('shipments', 'receiver_name')
    op.drop_column('shipments', 'sender_name')
    # ### end Alembic commands ###
