"""add lat lng to vehicle

Revision ID: 184d759843e9
Revises: 2c8a8888f7d3
Create Date: 2026-07-11 11:46:01.818590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184d759843e9'
down_revision: Union[str, Sequence[str], None] = '2c8a8888f7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('current_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'current_lng')
    op.drop_column('vehicles', 'current_lat')
    # ### end Alembic commands ###
