"""add photo_url and reset token fields to user

Revision ID: 2c8a8888f7d3
Revises: cbf6fed65b6d
Create Date: 2026-07-10 15:24:05.469637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8a8888f7d3'
down_revision: Union[str, Sequence[str], None] = 'cbf6fed65b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
