"""create drivers table

Revision ID: 2e239738e21c
Revises: 9b3d6e0a25a5
Create Date: 2026-07-18 21:17:32.395152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e239738e21c'
down_revision: Union[str, Sequence[str], None] = '9b3d6e0a25a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('drivers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('drivers', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('drivers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('drivers', 'name')
    # ### end Alembic commands ###
