"""add maintenance table

Revision ID: 33cadea1ae5f
Revises: f3d82460ab47
Create Date: 2026-08-06 12:53:20.797299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cadea1ae5f'
down_revision: Union[str, Sequence[str], None] = 'f3d82460ab47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_category', sa.String(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('next_service_date', sa.DateTime(), nullable=False),
    sa.Column('service_cost', sa.Float(), nullable=False),
    sa.Column('service_provider', sa.String(), nullable=False),
    sa.Column('maintenance_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_id'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
