"""add_fuel_record_table

Revision ID: 4aee8a91ec5e
Revises: e9bf3448b366
Create Date: 2026-08-06 17:46:19.506896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aee8a91ec5e'
down_revision: Union[str, Sequence[str], None] = 'e9bf3448b366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('fuel_quantity', sa.Float(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('fuel_date', sa.Date(), nullable=False),
    sa.Column('fuel_station', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_records_id'), 'fuel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_records_id'), table_name='fuel_records')
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
