"""add pickup and destination coordinates to trip

Revision ID: 4e1cbaccd0a6
Revises: f017180a2549
Create Date: 2026-07-16 11:05:39.177720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1cbaccd0a6'
down_revision: Union[str, Sequence[str], None] = 'f017180a2549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('pickup_lng', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_lat', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_lng')
    op.drop_column('trips', 'destination_lat')
    op.drop_column('trips', 'pickup_lng')
    op.drop_column('trips', 'pickup_lat')
    # ### end Alembic commands ###
