"""add_trip_location_updated_at

Revision ID: 505054d898a0
Revises: 634ab6c70858
Create Date: 2026-08-13 23:56:58.632814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505054d898a0'
down_revision: Union[str, Sequence[str], None] = '634ab6c70858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'location_updated_at')
    # ### end Alembic commands ###
