"""Add location fields to driver

Revision ID: 5d21179c9381
Revises: f9354262b32f
Create Date: 2026-08-11 15:04:22.435085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d21179c9381'
down_revision: Union[str, Sequence[str], None] = 'f9354262b32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('current_longitude', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True))
    
    bind = op.get_context().bind
    inspector = sa.inspect(bind)
    has_updated_at = False
    for col in inspector.get_columns('trips'):
        if col['name'] == 'updated_at':
            has_updated_at = True
            break
            
    if not has_updated_at:
        op.add_column('trips', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    else:
        op.alter_column('trips', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('drivers', 'location_updated_at')
    op.drop_column('drivers', 'current_longitude')
    op.drop_column('drivers', 'current_latitude')
    # ### end Alembic commands ###
