"""Add foreign key indexes

Revision ID: 634ab6c70858
Revises: 5d21179c9381
Create Date: 2026-08-13 18:34:37.117862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634ab6c70858'
down_revision: Union[str, Sequence[str], None] = '5d21179c9381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_vehicle_id'), 'driver_assignments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_shipments_assigned_driver_id'), 'shipments', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_shipments_assigned_vehicle_id'), 'shipments', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_shipments_assigned_vehicle_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_driver_id'), table_name='shipments')
    op.drop_index(op.f('ix_driver_assignments_vehicle_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    # ### end Alembic commands ###
