"""Fuel

Revision ID: 6a3a56c40797
Revises: 8f2f063ba9da
Create Date: 2026-08-03 14:38:49.742802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3a56c40797'
down_revision: Union[str, Sequence[str], None] = '8f2f063ba9da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('fuel_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_quantity', sa.Float(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('fuel_station', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_records_id'), 'fuel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fuel_records_id'), table_name='fuel_records')
    op.drop_table('fuel_records')
    # ### end Alembic commands ###
