"""Update maintenance model

Revision ID: 75c2f1568981
Revises: c71d1f6866a6
Create Date: 2026-07-27 19:54:44.599572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c2f1568981'
down_revision: Union[str, Sequence[str], None] = 'c71d1f6866a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('maintenance_category', sa.String(), nullable=False))
    op.add_column('maintenance', sa.Column('service_date', sa.Date(), nullable=True))
    op.add_column('maintenance', sa.Column('next_service_date', sa.Date(), nullable=True))
    op.add_column('maintenance', sa.Column('service_cost', sa.Float(), nullable=True))
    op.add_column('maintenance', sa.Column('service_provider', sa.String(), nullable=True))
    op.add_column('maintenance', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('maintenance', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('maintenance', sa.Column('is_active', sa.Integer(), nullable=True))
    op.alter_column('maintenance', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('maintenance', 'maintenance_type')
    op.drop_column('maintenance', 'completed_date')
    op.drop_column('maintenance', 'scheduled_date')
    op.drop_column('maintenance', 'remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('maintenance', sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('maintenance', sa.Column('completed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('maintenance', sa.Column('maintenance_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('maintenance', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('maintenance', 'is_active')
    op.drop_column('maintenance', 'created_at')
    op.drop_column('maintenance', 'notes')
    op.drop_column('maintenance', 'service_provider')
    op.drop_column('maintenance', 'service_cost')
    op.drop_column('maintenance', 'next_service_date')
    op.drop_column('maintenance', 'service_date')
    op.drop_column('maintenance', 'maintenance_category')
    # ### end Alembic commands ###
