"""extend_trip_model

Revision ID: 7737becec572
Revises: f499f29392be
Create Date: 2026-07-17 15:10:27.423945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7737becec572'
down_revision: Union[str, Sequence[str], None] = 'f499f29392be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('distance_km', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('estimated_duration', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('route_summary', sa.String(length=500), nullable=True))
    op.add_column('trips', sa.Column('route_geometry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'route_geometry')
    op.drop_column('trips', 'route_summary')
    op.drop_column('trips', 'estimated_duration')
    op.drop_column('trips', 'distance_km')
    # ### end Alembic commands ###
