"""update_vehicle_table

Revision ID: 7f8e47f85fa7
Revises: 4778d4a6edee
Create Date: 2026-07-10 16:51:12.318647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8e47f85fa7'
down_revision: Union[str, Sequence[str], None] = '4778d4a6edee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('status', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('manufacturer', sa.String(), nullable=False))
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vehicles', 'manufacturer')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'status')
    # ### end Alembic commands ###
