"""add created_at to shipment

Revision ID: 80b95c31bb0e
Revises: 6847dee00438
Create Date: 2026-08-04 21:17:20.254952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b95c31bb0e'
down_revision: Union[str, Sequence[str], None] = '6847dee00438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_alerts_id'), table_name='maintenance_alerts')
    op.drop_table('maintenance_alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alert_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_status', sa.VARCHAR(), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('generated_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('next_service_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], name=op.f('maintenance_alerts_maintenance_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_alerts_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_alerts_pkey'))
    )
    op.create_index(op.f('ix_maintenance_alerts_id'), 'maintenance_alerts', ['id'], unique=False)
    # ### end Alembic commands ###
