"""add created_at to trips

Revision ID: 9b3d6e0a25a5
Revises: d310beb6166a
Create Date: 2026-07-18 20:36:19.515183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3d6e0a25a5'
down_revision: Union[str, Sequence[str], None] = 'd310beb6166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'created_at')
    # ### end Alembic commands ###
