"""add fleet fuel records

Revision ID: 9b52b8e0673b
Revises: da10cb19a7b9
Create Date: 2026-08-03 18:50:15.095026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b52b8e0673b'
down_revision: Union[str, Sequence[str], None] = 'da10cb19a7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fleet_fuel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('fuel_quantity', sa.Float(), nullable=False),
    sa.Column('fuel_cost', sa.Float(), nullable=False),
    sa.Column('odometer_reading', sa.Float(), nullable=False),
    sa.Column('fuel_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fuel_station', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fleet_fuel_records_id'), 'fleet_fuel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fleet_fuel_records_id'), table_name='fleet_fuel_records')
    op.drop_table('fleet_fuel_records')
    # ### end Alembic commands ###
