"""add status and next_service_date to maintenance_alerts

Revision ID: aa7496de16a6
Revises: 97c24a57cbb2
Create Date: 2026-08-05 08:33:50.482224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7496de16a6'
down_revision: Union[str, Sequence[str], None] = '97c24a57cbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_alerts', sa.Column('status', sa.Enum('pending', 'sent', 'completed', name='alertstatus'), nullable=True))
    op.add_column('maintenance_alerts', sa.Column('next_service_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_alerts', 'next_service_date')
    op.drop_column('maintenance_alerts', 'status')
    # ### end Alembic commands ###
