"""add notification frequency and company settings

Revision ID: aec1e823451a
Revises: 4e1cbaccd0a6
Create Date: 2026-07-16 15:05:10.952050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec1e823451a'
down_revision: Union[str, Sequence[str], None] = '4e1cbaccd0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_frequency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_frequency')
    # ### end Alembic commands ###
