"""Create trips table

Revision ID: b0b1c7b586bb
Revises: 54a66e788449
Create Date: 2026-07-11 21:49:02.438141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0b1c7b586bb'
down_revision: Union[str, Sequence[str], None] = '54a66e788449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.String(), nullable=False),
    sa.Column('end_location', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=True),
    sa.Column('expected_arrival', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.add_column('shipments', sa.Column('sender_name', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('receiver_name', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('current_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'current_location')
    op.drop_column('shipments', 'receiver_name')
    op.drop_column('shipments', 'sender_name')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
