"""Add current coordinates to Trip

Revision ID: b850a229bd23
Revises: 7737becec572
Create Date: 2026-07-23 20:52:03.270657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b850a229bd23'
down_revision: Union[str, Sequence[str], None] = '7737becec572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('current_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    
    # Enum updates cannot happen inside a transaction
    connection = op.get_bind()
    connection.execute(sa.text("COMMIT"))
    connection.execute(sa.text("ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'picked_up'"))
    connection.execute(sa.text("ALTER TYPE shipment_status ADD VALUE IF NOT EXISTS 'out_for_delivery'"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'current_longitude')
    op.drop_column('trips', 'current_latitude')
    # ### end Alembic commands ###
