"""Driver Assignment and Attendance

Revision ID: be612fad1bf3
Revises: 6a3a56c40797
Create Date: 2026-08-03 14:56:47.468417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be612fad1bf3'
down_revision: Union[str, Sequence[str], None] = '6a3a56c40797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('attendance_status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='attendancestatus'), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_attendance_id'), 'driver_attendance', ['id'], unique=False)
    op.create_table('driver_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assignment_status', sa.Enum('ASSIGNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='assignmentstatus'), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_assignments_id'), 'driver_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_assignments_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_driver_attendance_id'), table_name='driver_attendance')
    op.drop_table('driver_attendance')
    # ### end Alembic commands ###
