"""add created_at to shipments

Revision ID: c71d1f6866a6
Revises: 7c0d36e99510
Create Date: 2026-07-21 12:25:12.576812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71d1f6866a6'
down_revision: Union[str, Sequence[str], None] = '7c0d36e99510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'created_at')
    # ### end Alembic commands ###
