"""add trip start coordinates

Revision ID: cea0682fbac5
Revises: 90c3bda347a8
Create Date: 2026-08-11 15:00:58.555996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cea0682fbac5'
down_revision: Union[str, Sequence[str], None] = '90c3bda347a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('trips', sa.Column('start_latitude', sa.String(), nullable=False))
    op.add_column('trips', sa.Column('start_longitude', sa.String(), nullable=False))
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trips', 'destination_latitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trips', 'destination_longitude',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(
    'trips',
    'departure_time',
    existing_type=sa.VARCHAR(),
    type_=sa.DateTime(),
    existing_nullable=True,
    postgresql_using='departure_time::timestamp without time zone'
)
    op.alter_column(
    'trips',
    'expected_arrival',
    existing_type=sa.VARCHAR(),
    type_=sa.DateTime(),
    existing_nullable=True,
    postgresql_using='expected_arrival::timestamp without time zone'
)
    op.drop_column('trips', 'created_at')
    op.drop_column('trips', 'actual_arrival')
    op.drop_column('trips', 'distance')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('trips', sa.Column('distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('actual_arrival', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('trips', 'expected_arrival',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'departure_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('trips', 'destination_longitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'destination_latitude',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trips', 'shipment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('trips', 'start_longitude')
    op.drop_column('trips', 'start_latitude')
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('maintenance_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alert_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alert_status', sa.VARCHAR(), server_default=sa.text("'Pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('generated_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('next_service_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.id'], name=op.f('maintenance_alerts_maintenance_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('maintenance_alerts_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maintenance_alerts_pkey'))
    )
    # ### end Alembic commands ###
