"""add driver experience and attendance fields

Revision ID: d03a80c0f82d
Revises: aec1e823451a
Create Date: 2026-07-19 15:01:19.288843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03a80c0f82d'
down_revision: Union[str, Sequence[str], None] = 'aec1e823451a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('drivers', sa.Column('attendance_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'attendance_percentage')
    op.drop_column('drivers', 'experience_years')
    # ### end Alembic commands ###
