"""Add foreign keys to trips

Revision ID: d310beb6166a
Revises: 481b035618b7
Create Date: 2026-07-14 20:50:03.583085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd310beb6166a'
down_revision: Union[str, Sequence[str], None] = '481b035618b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'shipments', ['shipment_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    # ### end Alembic commands ###
