"""Add GPS fields to trips

Revision ID: ecb10596c4bb
Revises: b0b1c7b586bb
Create Date: 2026-07-12 11:13:11.456929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb10596c4bb'
down_revision: Union[str, Sequence[str], None] = 'b0b1c7b586bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('current_latitude', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('current_longitude', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('destination_latitude', sa.String(), nullable=True))
    op.add_column('trips', sa.Column('destination_longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'current_longitude')
    op.drop_column('trips', 'current_latitude')
    # ### end Alembic commands ###
