"""add shipment_id to trip and reverse relationships

Revision ID: f017180a2549
Revises: 16bed5c476fd
Create Date: 2026-07-15 09:54:13.353494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f017180a2549'
down_revision: Union[str, Sequence[str], None] = '16bed5c476fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('shipment_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'trips', ['shipment_id'])
    op.create_foreign_key(None, 'trips', 'shipments', ['shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_column('trips', 'shipment_id')
    # ### end Alembic commands ###
