"""add_trip_coordinates

Revision ID: f499f29392be
Revises: 879b63d35b68
Create Date: 2026-07-16 13:58:47.697094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f499f29392be'
down_revision: Union[str, Sequence[str], None] = '879b63d35b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('pickup_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('pickup_longitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_latitude', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('destination_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination_longitude')
    op.drop_column('trips', 'destination_latitude')
    op.drop_column('trips', 'pickup_longitude')
    op.drop_column('trips', 'pickup_latitude')
    # ### end Alembic commands ###
