"""Add relationships

Revision ID: 0df2a0732f33
Revises: fb3f5ef48d72
Create Date: 2026-07-08 17:18:15.820715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df2a0732f33'
down_revision: Union[str, Sequence[str], None] = 'fb3f5ef48d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('drivers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('drivers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.add_column('shipments', sa.Column('eta', sa.String(), nullable=True))
    op.add_column('shipments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('shipments', 'driver_id')
    op.drop_column('shipments', 'vehicle_id')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    op.add_column('vehicles', sa.Column('registration_number', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('vehicle_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('capacity', sa.Integer(), nullable=False))
    op.add_column('vehicles', sa.Column('fuel_type', sa.String(), nullable=False))
    op.add_column('vehicles', sa.Column('current_status', sa.String(), nullable=True))
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('vehicles_license_plate_key'), 'vehicles', type_='unique')
    op.create_unique_constraint(None, 'vehicles', ['registration_number'])
    op.drop_column('vehicles', 'make')
    op.drop_column('vehicles', 'status')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'year')
    op.drop_column('vehicles', 'license_plate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('license_plate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('vehicles', sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.create_unique_constraint(op.f('vehicles_license_plate_key'), 'vehicles', ['license_plate'], postgresql_nulls_not_distinct=False)
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'is_active')
    op.drop_column('vehicles', 'current_status')
    op.drop_column('vehicles', 'fuel_type')
    op.drop_column('vehicles', 'capacity')
    op.drop_column('vehicles', 'vehicle_type')
    op.drop_column('vehicles', 'registration_number')
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.add_column('shipments', sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('driver_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('shipments', 'created_at')
    op.drop_column('shipments', 'eta')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.alter_column('drivers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('drivers', 'created_at')
    op.drop_column('drivers', 'is_active')
    op.drop_column('drivers', 'email')
    # ### end Alembic commands ###
