"""Add trip completion timestamp

Revision ID: 5d755891b5f9
Revises: 2c28c9b32517
Create Date: 2026-08-15 12:41:36.867371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d755891b5f9'
down_revision: Union[str, Sequence[str], None] = '2c28c9b32517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'completed_at')
    # ### end Alembic commands ###
