"""Add maintenance table

Revision ID: 5d890df0a97f
Revises: 9aa2ca8d9778
Create Date: 2026-08-13 19:38:48.180505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d890df0a97f'
down_revision: Union[str, Sequence[str], None] = '9aa2ca8d9778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_category', sa.String(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=False),
    sa.Column('service_provider', sa.String(), nullable=False),
    sa.Column('maintenance_status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_id'), 'maintenance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_id'), table_name='maintenance')
    op.drop_table('maintenance')
    # ### end Alembic commands ###
