"""add_maintenance_records_table

Revision ID: 8fc314d07745
Revises: d3e4f5g6h7i8
Create Date: 2026-07-27 19:36:44.063619

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8fc314d07745'
down_revision: str | Sequence[str] | None = 'd3e4f5g6h7i8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('OIL_CHANGE', 'TYRE_REPLACEMENT', 'BRAKE_SERVICE', 'ENGINE_SERVICE', 'GENERAL_INSPECTION', name='maintenancecategoryenum'), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('service_cost', sa.Float(), nullable=True),
    sa.Column('service_provider', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatusenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_vehicle_id'), 'maintenance_records', ['vehicle_id'], unique=False)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'sender_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'delivery_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('shipments', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_trips_driver_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_status'), table_name='trips')
    op.drop_index(op.f('ix_trips_vehicle_id'), table_name='trips')
    op.drop_constraint(op.f('trips_vehicle_id_fkey'), 'trips', type_='foreignkey')
    op.drop_constraint(op.f('trips_driver_id_fkey'), 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'trips', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key(op.f('trips_driver_id_fkey'), 'trips', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('trips_vehicle_id_fkey'), 'trips', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_trips_vehicle_id'), 'trips', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_trips_status'), 'trips', ['status'], unique=False)
    op.create_index(op.f('ix_trips_driver_id'), 'trips', ['driver_id'], unique=False)
    op.alter_column('shipments', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('shipments', 'delivery_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'receiver_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'sender_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_maintenance_records_vehicle_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
