"""Update shipment model for milestone 2

Revision ID: c14e6a55308b
Revises: f61746ce2633
Create Date: 2026-07-13 19:49:47.759388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14e6a55308b'
down_revision: Union[str, Sequence[str], None] = 'f61746ce2633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('tracking_number', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('sender_name', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('receiver_name', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('pickup_location', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('delivery_location', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('current_status', sa.String(), nullable=False))
    op.add_column('shipments', sa.Column('weight', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'shipments', ['tracking_number'])
    op.create_foreign_key(None, 'shipments', 'drivers', ['driver_id'], ['id'])
    op.drop_column('shipments', 'eta')
    op.drop_column('shipments', 'destination')
    op.drop_column('shipments', 'origin')
    op.drop_column('shipments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('origin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shipments', sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shipments', sa.Column('eta', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='unique')
    op.drop_column('shipments', 'weight')
    op.drop_column('shipments', 'current_status')
    op.drop_column('shipments', 'delivery_location')
    op.drop_column('shipments', 'pickup_location')
    op.drop_column('shipments', 'receiver_name')
    op.drop_column('shipments', 'sender_name')
    op.drop_column('shipments', 'tracking_number')
    op.drop_column('shipments', 'driver_id')
    # ### end Alembic commands ###
