"""Add vehicle location

Revision ID: e7b89a87e006
Revises: 28ee6f333540
Create Date: 2026-08-20 14:53:47.795794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b89a87e006'
down_revision: Union[str, Sequence[str], None] = '28ee6f333540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_latitude', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('current_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'current_longitude')
    op.drop_column('vehicles', 'current_latitude')
    # ### end Alembic commands ###
