"""add_driver_assignment_attendance_status

Revision ID: ee417dc7edf5
Revises: 8fc314d07745
Create Date: 2026-07-29 21:09:49.013506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee417dc7edf5'
down_revision: Union[str, Sequence[str], None] = '8fc314d07745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='attendancestatusenum'), nullable=False),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id', 'date', name='uq_driver_attendance_date')
    )
    op.create_index(op.f('ix_driver_attendance_driver_id'), 'driver_attendance', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_attendance_id'), 'driver_attendance', ['id'], unique=False)
    op.create_table('driver_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('assignment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='assignmentstatusenum'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_id'), 'driver_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_trip_id'), 'driver_assignments', ['trip_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_vehicle_id'), 'driver_assignments', ['vehicle_id'], unique=False)
    # Create the driverstatusenum type before using it in ADD COLUMN
    driver_status_enum = sa.Enum('AVAILABLE', 'ON_DUTY', 'OFF_DUTY', name='driverstatusenum')
    driver_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('drivers', sa.Column('status', sa.Enum('AVAILABLE', 'ON_DUTY', 'OFF_DUTY', name='driverstatusenum'), nullable=False, server_default='AVAILABLE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'status')
    sa.Enum(name='driverstatusenum').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_driver_assignments_vehicle_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_trip_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_index(op.f('ix_driver_attendance_id'), table_name='driver_attendance')
    op.drop_index(op.f('ix_driver_attendance_driver_id'), table_name='driver_attendance')
    op.drop_table('driver_attendance')
    # ### end Alembic commands ###
