"""Add foreign key relationships

Revision ID: f61746ce2633
Revises: 0df2a0732f33
Create Date: 2026-07-08 17:46:43.239641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61746ce2633'
down_revision: Union[str, Sequence[str], None] = '0df2a0732f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'drivers', ['user_id'])
    op.create_foreign_key(None, 'drivers', 'users', ['user_id'], ['id'])
    op.add_column('shipments', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shipments', 'vehicles', ['vehicle_id'], ['id'])
    op.add_column('vehicles', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'vehicles', ['driver_id'])
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='unique')
    op.drop_column('vehicles', 'driver_id')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'vehicle_id')
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'user_id')
    # ### end Alembic commands ###
