from .user import User
from .driver import Driver
from .vehicle import Vehicle
from .shipment import Shipment
from .notification import Notification
from .settings import Settings
from .trip import Trip
from .maintenance import Maintenance
from .driver_assignment import DriverAssignment
from .driver_attendance import DriverAttendance