"""add pickup and destination to trips

Revision ID: dfbd1d67e725
Revises: 4bd28fa37663
Create Date: 2026-07-17 17:45:34.936566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbd1d67e725'
down_revision: Union[str, Sequence[str], None] = '4bd28fa37663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'trips',
        sa.Column(
            'pickup_location',
            sa.String(),
            nullable=False,
            server_default='Unknown'
        )
    )

    op.add_column(
        'trips',
        sa.Column(
            'destination',
            sa.String(),
            nullable=False,
            server_default='Unknown'
        )
    )

    # Remove the defaults after existing rows have been populated
    op.alter_column('trips', 'pickup_location', server_default=None)
    op.alter_column('trips', 'destination', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination')
    op.drop_column('trips', 'pickup_location')
    # ### end Alembic commands ###
